services:
  nextcloud_db:
    container_name: nextcloud-db
    image: mariadb:11.4-noble #LTS Long Time Support Until May 29, 2029.
    security_opt:
      - no-new-privileges:false
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-read-only-compressed=OFF
    volumes:
      - /volume1/docker/nextcloud/db:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT_PASS
      - MYSQL_PASSWORD=NEXTCLOUD_DB_PASS
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
      - TZ=Europe/Berlin
    restart: unless-stopped
      
  redis:
    image: redis
    container_name: nextcloud-redis
    hostname: nextcloud_redis
    user: 1000:10
    healthcheck:
     test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - /volume1/docker/nextcloud/redis:/data:rw
    environment:
      TZ: Europe/Berlin
    restart: unless-stopped
      
  nextcloud:
    container_name: nextcloud
    ports:
      - 8082:80
    depends_on:
      nextcloud_db:
       condition: service_started
      redis:
       condition: service_healthy
    environment:
      - REDIS_HOST=nextcloud_redis
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=ADMIN_PASS
      - NEXTCLOUD_TRUSTED_DOMAINS=YOUR_DOMAIN,192.168.*.*
      - OVERWRITEPROTOCOL=https
      - MYSQL_PASSWORD=NEXTCLOUD_DB_PASS
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    volumes:
      - /volume1/docker/nextcloud/html:/var/www/html:rw
      - /volume1/docker/nextcloud/custom_apps:/var/www/html/custom_apps:rw
      - /volume1/docker/nextcloud/config:/var/www/html/config:rw
      - /volume1/docker/nextcloud/data:/var/www/html/data:rw
      - /volume1/docker/nextcloud/themes:/var/www/html/themes:rw
    image: nextcloud:latest
    restart: unless-stopped
    
  cron:
   image: nextcloud:apache
   container_name: nextcloud-cron
   restart: unless-stopped
   volumes:
     - /volume1/docker/nextcloud/config:/var/www/html/config:rw
     - /volume1/docker/nextcloud/html:/var/www/html:rw
     - /volume1/docker/nextcloud/custom_apps:/var/www/html/custom_apps:rw
     - /volume1/docker/nextcloud/data:/var/www/html/data:rw
   entrypoint: /cron.sh
   depends_on:
    nextcloud_db:
       condition: service_started
    redis:
       condition: service_started
