services:
  homepage:
    container_name: homepage
    image: gethomepage/homepage:latest
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.50.243:3550,ANOTHER_HOSTNAME
    ports:
      - 3550:3000
    volumes:
      - /volume1/docker/homepage:/app/config:rw
      - /volume1/docker/homepage/public:/app/public/images:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
